### ISSUE TITLE
Tracklist not shown in Chrome

### ISSUE THREAD

**Issue by wdlb** [adlawson/mixcloud-tracklist#31]
I used this mix: [https://www.mixcloud.com/Todomundo/working-women-present-crown-shyness/](url)

In Firefox 54.0.1 with mixcloud-tracklist 4.2.0 the tracklist is shown.

In Chrome 60.0.3112.90 with mixcloud-tracklist 4.2.0 the tracklist is not shown. I went to Developer Tools, and the data.cloudcast.sections  variable on line 63821 of mixcloud-tracklist.js is an empty array. I attached a copy of the response and data variables to this issue.

Do you have an idea on how to fix this? Thanks a lot, I really enjoy using your extension.

[variables.zip](https://github.com/adlawson/mixcloud-tracklist/files/1211247/variables.zip)

**Comment by deoney** [comment]
Same prob here..

**Comment by adlawson** [comment]
Hey @wdlb, if `data.cloudcast.sections` is empty, then it's because the uploader hasn't attached a tracklist to the mix. In those cases, there's nothing I can do to generate a tracklist.

I have just checked out that mix on the site, and the `data.cloudcast.sections` now includes data, so it could be a delay in updating the cache either in Mixcloud, or the response was cached by your browser.
```json
"sections": [
{
"start_time": 0,
"artist": "E + E",
"title": "Fire Gut,"
},
{
"start_time": 225,
"artist": "Yves Tumor",
"title": "Limerence,"
},
{
"start_time": 527,
"artist": "Frank Harris & Maria Marquez",
"title": "Loveroom,"
},
{
"start_time": 774,
"artist": "Prefab Sprout",
"title": "I Remember That,"
},
...
```

There is another error at the moment though, where even though all data is available, tracklists are _still_ not being displayed. It seems that in the last day or so, Mixcloud have added a redirect in their API that is not followed.

I'll add a separate issue for that.
